### ISSUE TITLE
Feature:  User can view a random monster card on page load and upon request.

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/ygo-like-or-strike#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can view a random monster card on page load and upon request.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the page loads, the user is presented with a random YGO monster. They can press the New Card button to display a new YGO monster.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View New Card](https://user-images.githubusercontent.com/78003700/163853020-b4bdf4dc-fd4b-4869-9e2f-8166499f92d7.png)
![View New Card Desktop](https://user-images.githubusercontent.com/78003700/163853071-8ba583c0-421a-4f73-b210-7791f6f69213.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML CSS Structure
	- [x] Navbar
	- [x] Card Title
	- [x] Image Container
	- [x] New Card Button
- [x] Add an ID for each card display element `#cardTitle` and `#cardImage`
- [x] Define a function that pulls all Monster Cards from the API and returns them into an object for card data that is stored in Local Storage (`cardData`)
- [x] Define a function `displayNewCard(card)` that takes a card object as an argument and changes the content of `#cardTitle` and `#cardImage` according to the argument.
- [x] Define a function `drawNewCard()` that takes a random card from `cardData` array and then displays it via `displayNewCard(card)`
- [x] Attach `drawNewCard()` as an event handler to the button on `'click'`.
- [x] Get `drawNewCard()` to occur after the API request completes and creates the `cardData` in local storage.

---

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
