### ISSUE TITLE
Feature: User can like or dislike the card 

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/ygo-like-or-strike#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like or dislike the card.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is given two buttons to Like or Dislike the card. Upon selection, play animation, and store user's rating in user data model.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Dislike Card](https://user-images.githubusercontent.com/78003700/163897901-147d5e35-d705-46f3-aa02-2bbaff4f4121.png)
![Like or Dislike Cards](https://user-images.githubusercontent.com/78003700/163897905-1a721ef5-e0fb-40da-8f2e-186c8bb79193.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Import Font Awesome
- [x] Create Like/Dislike Buttons in HTML CSS using symbols from Font Awesome
- [x] Create `userData` and save to Local Storage
	- [x] include an array `rated` containing objects for each card object + `rating` property which shows whether something is liked or not.
- [x] Listen for clicks on like/dislike buttons. On click, push current card to `userData.rated` with `rating` attribute set in accordance to input.
- [x] On page load, iterate through `userData.ratings` array. For each card, remove the corresponding card in `cardData`.
- [x] Display remaining cards (`cardData.length`) below New Card button.

---

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
