### ISSUE TITLE
Feature: User can view the cards they have rated

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/ygo-like-or-strike#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the cards they have rated
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can navigate to Results page and view all the cards they have rated. They can then select which cards they want to view from Liked, Striked, or all.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 1](https://user-images.githubusercontent.com/78003700/164110719-966e2e0a-283e-4699-ae88-1d574c44c4c8.png)
![aaaa](https://user-images.githubusercontent.com/78003700/164110728-5ccbf50c-55de-4f7a-b7a7-1f4680178848.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Import and map icon folder paths to an object `iconsMD`
- [x] Split `<main>` and `header` into 2 `div` elements for views, `data-view=rating` and `results`
- [x] HTML CSS for `Results` button that leads to `data-view=results`
- [x] HTML CSS for alternate header with `back` button that returns to `data-view=rating`
- [x] Create view swap handler function that uses `.hidden` and attach to navigation buttons
  - (If user switched back to `data-view=rating`, the images don't unload.)
- [x] In `results` view, create DOM Skeleton for cards
	- [x] Define function to handle DOM creation of card entry and attach `data-card-id` to each one
	- [x] Create simplified DOM Skeleton for cards for when `userCards > 50`, and redraw all card entries with simplified DOM skeleton if `userCards` breaches threshold. 
- [x]  Upon user data load and update, append to results view.
- [x] In `results` view, create row for rating visibility options, and within it, the label block and buttons.
- [x] Create `resultsShowOnly(rating)` function that adds `.hidden` class to all cards that aren't the specified rating, and attach to rating visibility option buttons.

---

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
