### ISSUE TITLE
Feature: User can sort their card view by archetype

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/ygo-like-or-strike#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sort their card view by archetype
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can select option to sort all cards by archetype. They can see how many cards they have rated within the archetype, as well as expand/minimize the sections that they want to focus on.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

 
![NEW Sort Results Mobile](https://user-images.githubusercontent.com/78003700/164330228-1a8f23c9-6669-4f8a-8d6a-21235e03fc85.png)
![NEW Sort Results Desktop](https://user-images.githubusercontent.com/78003700/164330241-5631458d-cabe-4042-b58b-4c92d0a5fdd5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTMLCSS for new top sorting buttons that are positioned based on screen width
- [x] Create HTMLCSS Skeleton for Archetype headers.
- [x] Attach listeners to "Sort By Archetype" options and "Order Rated" options, attach to associated handlers.
- [x] Create function that groups each card entry by archetype and assigns to object that keeps track of the state of the display
- [x] Create a function that renders each archetype alphabetically sectioned off with their own Archetype Headers
  - [x] When rendering, make sure each card within archetype is ordered by current `Order Rated` 
- [x] Listen to clicks on archetype header, toggle the right-side icon and hide cards within the Archetype.
- [x] Listen to clicks on Collapse All button. Goes through each archetype and toggles on/off the display of each one.

---

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
