### ISSUE TITLE
Feature: User can remove cards from either collection

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/ygo-like-or-strike#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove cards from either collection

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click Edit button, which allows them to click on elements that they want to delete. By pressing confirm, they are given a confirmation modal for the deletion. Pressing Yes will delete the entries and return to results view. Pressing No will go back to Edit view.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Delete Item](https://user-images.githubusercontent.com/78003700/163854105-818294cb-a521-42a2-9230-938d4ee4df3e.png)

![Delete Item Desktop](https://user-images.githubusercontent.com/78003700/163854112-11a39602-c1ac-4400-99a8-2c58466b8412.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create new "editing" header with "back" and "confirm" button.
- [x] Create Delete Modal HTML/CSS and hide for later.
- [x] Create class `.selected` and style accordingly for selected buttons
- [x] Create new view state "editing" for results view, which also changes the Header
	- [x] Disable all anchor tags.
	- [x] On entry click, add entry to `toDelete` array. Remove from `toDelete` if clicked again.
	- [x] Upon clicking confirm, show delete Modal and delete upon confirmation, as well as navigate back to normal results view.
	- [x] Upon clicking back, go back to normal results view and clear `toDelete` and `.selected` styling
- [x]  Create "Select All" button within `editing` view that appends all items to `toDelete` array

---

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
